name: neural_topology
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=21.0
  - numpy=1.24.4
  - matplotlib=3.4
  - scikit-learn=0.24
  - pytorch=1.8
  - torchvision=0.9
  - cpuonly
  - pip:
    - ripser==0.6.1
    - persim==0.3.1
    - gudhi==3.10.1
    - networkx==2.5
    - jupyter==1.0.0
    - tqdm
    - gymnasium
    - wandb

# pip install "gymnasium[mujoco]"
# pip install "gymnasium[other]"
# pip install "gymnasium[box2d]"