env_id: "BipedalWalker-v3" #"Walker2d" #"Hopper-v4"
seed: 1
hidden_szie: 64
total_timesteps: 1000000
learning_rate: 0.0003
num_envs: 1
num_steps: 2048
gamma: 0.99
gae_lambda: 0.95
num_minibatches: 32
update_epochs: 10
clip_coef: 0.2
clip_vloss: true   # was True in argparse
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
target_kl: 0.1
topology_analysis_interval: 50
save_checkpoint_interval: 100
capture_video: true  # was True in argparse